- .eslintignore
- demo/contractHost/bootstrap.js
- demo/contractHost/escrow.js
- demo/contractHost/vat-alice.js
- demo/contractHost/vat-bob.js
- demo/contractHost/vat-host.js
- demo/contractHost/vat-mint.js
- demo/left-right/bootstrap.js
- demo/left-right/vat-left.js
- demo/left-right/vat-right.js
- scripts/build-kernel.js
This PR reconfigures .eslintignore to remove SES-specific settings and add settings relevant to SwingSet. 
It also runs `npm run lint-fix` on the repo.
The last commit is a manual run through of the remaining issues. This probably needs an extra set of eyes to make sure the changes are correct. 
Closes #12
> Reconfigure .eslintignore and run lint-fix and do manual fixes

- src/kernel/makePromise.js
This PR (work done by @erights) deletes the `domain` property from any promises being created through `makePromise`. That may break some functionality, so there is also an option called `unsafe` that turns on an alternative. 
Closes #22
> Fix #22: Remove domain property from promise

- demo/contractHost/bootstrap.js
- demo/contractHost/vat-alice.js
- demo/contractHost/vat-bob.js
- demo/contractHost/vat-mint.js
- test/test-demos.js
This PR adds tests for the demos. 
Some changes needed to be made in how the demos are run. For instance, in order to not create duplicate code, most of the machinery of `bin/vat` was moved to a new file in `demo/` called `start.js` so that it could be used by the tests as well as the command line. I also needed to add the usual logging functionality to the `contractHost` demos. Lastly, I rewrote the part of the contractHost bootstrap function that controls which demo to run. It could probably go either way easily, but when I was writing the tests, I was getting silent failures when the option I was using wasn't recognized, so I turned it into a switch statement.
> Add tests for the demos

- src/devices/index.js
Fixes #51 
Add missing src/devices/index.js with named exports from the devices' top-halves.
> Reenable bin/vat

- demo/handoff/bootstrap.js
- demo/handoff/corkboard-assay.js
- demo/handoff/corkboard.js
- demo/handoff/handoff.js
- demo/handoff/vat-alice.js
- demo/handoff/vat-bob.js
- demo/handoff/vat-handoff.js
- test/test-demos.js
A simple Handoff service that can be provided to vats to allow them to set up channels ('corkboards') to share pointers with others.
There's more functionality that could be added, but it passes a three-vat test, enabling Alice to pass a value to Bob.
Next step if we like the current state is to add this to everyone's home list and validate that it works in that environment.
> A simple Handoff service 

- README.md
the directions yield:
```
$ ./bin/vat run demo/contractHost -- mint
= loading config from basedir demo/contractHost
(node:26959) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'demo/contractHost'
```
> README: prune reference to contractHost demo

- src/kernel/commsSlots/commsSlots.js
- src/kernel/commsSlots/outbound/mapOutbound.js
- src/kernel/commsSlots/state/CLists.js
- test/commsSlots/commsController/test-addEgress.js
- test/commsSlots/commsController/test-addIngress.js
- test/commsSlots/makeCommsSlots/test-deliver.js
- test/commsSlots/state/test-makeCLists.js
Previously, the commsSlots cLists assumed that a kernelSlot would map to a single machine. This PR adds a layer of flexibility such that a kernelSlot can map to multiple machines. 
Changes in CLists.js:
* `checkIfAlreadyExists` is changed to only error if both the kernelSlot and the outgoingWireMessage to be stored are the same (i.e. same kernelSlot for same other machine). 
* `mapKernelSlotToOutgoingWireMessage` takes in an additional parameter - `otherMachineName`
* a new function, `mapKernelSlotToOutgoingWireMessageList` is used when we don't yet know the machine to send a message to, and we only know the kernelToMeSlot this returns a list of outgoingWireMessages
* The `add` function adds the `outgoingWireMessageObj` to a map keyed on `otherMachineName`. This is what enables the lookup …
> Change CLists to allow mapping a single kernelSlot to multiple machines

- src/kernel/commsSlots/commsSlots.js
- src/kernel/commsSlots/inbound/inboundHandler.js
- src/kernel/commsSlots/inbound/mapInbound.js
- src/kernel/commsSlots/outbound/mapOutbound.js
- src/kernel/liveSlots.js
- src/kernel/vatManager.js
- test/commsSlots/makeCommsSlots/test-deliver.js
- test/commsSlots/makeCommsSlots/test-notifyFulfillToData.js
- test/commsSlots/makeCommsSlots/test-notifyFulfillToPresence.js
- test/test-kernel.js
This PR removes the incorrect casting (see below for explanation) and cleans up commsSlots. 
What was line [79 of mapOutbound.js]([mapOutbound.js line 79](https://github.com/Agoric/SwingSet/blob/a191a0cb5334dc591b96ead7821ba92200f27ad7/src/kernel/commsSlots/outbound/mapOutbound.js#L79)) has been put in a new function called mapResultSlot which does not do the casting but instead just stores the kernelSlot in the commsSlot cList as type 'resolver'. No matching promise is necessary for this case. 
Clean ups:
1. The `resolverID` that was passed in as the last argument of `deliver` has been changed to a full slot of type 'resolver'. 
2. In messages over the wire, all messages have an event now. Previously, event==='send' was the implicit default and this is now made explicit. 
3. For clarity, …
> Fix ertp-30

- .circleci/config.yml
- package.json
- test/test-node-version.js
There's a new ordering issue that requires Node.js >= v12.
closes #99
> require Node.js v12

- src/kernel/liveSlots.js
- test/basedir-promises-2/bootstrap.js
- test/basedir-promises-2/vat-left.js
- test/test-promises.js
refs #95
I think this one will fix everything that can be fixed. `x!foo()` returns unfrozen Promises, because we have no place to freeze them, but `E(x).foo()` and `E(E(x).foo()).bar()` are both frozen.
I upgraded SwingSet trunk to eventual-send-0.2.0, so we should no longer be sometimes getting frozen promises from Promise `.post()` methods.
> harden E() result promises

- package-lock.json
- package.json
- src/controller.js
This new module encapsulates all the options we want to pass down to realms-shim or @agoric/evaluate.
Notably, it also backs out @agoric/eventual-send@0.2.0 that broke ERTP in favour of 0.1.11 which only introduces proper asynchronous defences.
We really should release SwingSet 0.0.18 right away, as 0.0.17 was quite broken (out of memory errors).  We'll work on eventual-send@0.2.1, but more gradually to find and fix what was causing the breakage.
> @agoric/default-evaluate-options: use it

- .circleci/config.yml
- test/test-node-version.js
The Node 12 ordering differences were only tickled by a bug in
@agoric/eventual-send v0.2.x.  The new version installed in the
SwingSet dependencies does not have this problem.
fixes #99
> test/test-node-version.js: only require Node 11

- package-lock.json
- package.json
- src/kernel/liveSlots.js
- test/test-liveslots.js
This should fix #131 and change liveSlots to pipeline messages into the kernel. In particular, this pattern:
```
const p1 = E(x).pipe1();
const p2 = E(p1).pipe2();
E(p2).pipe3();
```
should invoke `syscall.send()` three times before the Vat's turn finishes, one per `pipeNN` call. The second two will target a kernel promise, rather than a regular object import.
For now, the second two messages will be queued in the kernel, inside the `kernelPromises` table entry for p1/p2, in the `.queue` property. After the #88 changes land, the kernel will be able to deliver these to the comms vat directly, instead of queueing them.
> enable pipelining in liveslots-to-kernel

- test/test-kernel.js
- test/test-marshal.js
This is effectively a rebase of #133 on top of the (extensive) changes
wrought by #88. But it was achieved by just inserting the same function
wrapper around the whole file and then re-running 'npm run eslint-fix' to
adjust the indentation.
Run 'git diff -w' to see that there were no unexpected semantic changes.
closes #133
refs #130
> change some tests into importable modules, to test under XS

- src/build-source-bundle.js
- src/controller.js
We define vats (and devices) as a source file which contains a default export
named `setup()` which accepts a syscall function and returns a dispatch
function. But it would be nice to allow additional exports, so unit tests can
exercise subsets of the functionality.
This was difficult because our use of 'rollup' produced varying export names.
If the vat/device module had only a default export (e.g. `export default
function setup(){}`), the return value of rollup `R` would be exactly that
function: `dispatch = R(syscall)`. But if the module also had non-default
exports (e.g. `export default function setup(){}` and `export function
other(){}`), the return value would be an object with both `.default` and
`.other` properties, so `dispatch = R.default(syscall)`.
This patch changes the options …
> tolerate vats/devices with non-default exports

- package-lock.json
- package.json
This fixes a sandbox escape in the realms-shim, described in
https://github.com/Agoric/realms-shim/issues/48
> upgrade to SES v0.6.1

- src/controller.js
- src/kernel/id.js
- src/kernel/kernel.js
- src/kernel/state/deviceKeeper.js
- src/kernel/state/kernelKeeper.js
- src/kernel/state/vatKeeper.js
- test/test-controller.js
- test/test-devices.js
- test/test-kernel.js
- test/test-liveslots.js
.. as the index for kernel state data structures, instead of user-provided
vatName/deviceName strings. This will make it easier to use key/value state
storage (#144), since the keys will be more uniform (and shorter, and not
vulnerable to people using the separator string in their vat name). They look
like "vNN" and "dNN", where NN is a positive integer.
This will also make adding dynamic Vats easier (#19), as we'll just increment
a counter instead of asking the user to invent a unique name.
closes #146
> Use (mostly numeric) vatID/deviceID everywhere within kernel

- package-lock.json
- package.json
- src/controller.js
- src/kernel/liveSlots.js
- test/test-marshal.js
This change should now be ready to land with `@agoric/eventual-send@0.3.2` and the rebuilt `@agoric/default-evaluate-options` and `@agoric/evaluate`.
Closes https://github.com/Agoric/SwingSet/issues/106
Closes Agoric/eventual-send#30
> Move E() implementation to `@agoric/eventual-send`

- demo/encouragementBotCommsWavyDot/vat-bot.js
- demo/encouragementBotCommsWavyDot/vat-user.js
- src/kernel/liveSlots.js
This is the smallest possible change to support remote property lookup (via a round-trip).
Fixes https://github.com/Agoric/cosmic-swingset/issues/83
For completeness, support for property lookup should be plumbed into the pipelining architecture so that we can do something like:
```js
obj~.prop1~.prop2~.method(args)~.prop3~.method2(args2)
```
and have the whole thing be pipelined.
> liveSlots.js: makeQueued allow property lookup

- package-lock.json
- package.json
The prior eventual-send had a problem with the "override mistake" under SES.
Notably, the `HandledPromise` when it is a constructor, cannot also have a static `apply()` method, since that conflicts with `Function.prototype.apply`.
Working around this by not yet making it a constructor.
> deps: upgrade to working eventual-send
